package controllers

import (
	"cars/api/dto"
	"cars/models"
	"cars/pkg/httpx"
	"cars/pkg/logger"
	"cars/services"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	e "cars/pkg/errors"

	"github.com/go-chi/chi/v5"
)

// CarController manages HTTP requests related to cars.
type CarController struct {
	service services.CarService
}

// NewCarController creates a new instance of CarController.
func NewCarController(service services.CarService) *CarController {
	return &CarController{service: service}
}

// Get handles retrieving a car by its ID.
//
// Returns the car with the given ID, or a 404 error if the car is not found.
//
// Method: GET
// Path: /cars/{id}
func (c *CarController) Get(w http.ResponseWriter, r *http.Request) {
	log := logger.FromContext(r.Context())

	id := chi.URLParam(r, "id")

	car, err := c.service.Find(id)
	if err != nil {
		log.Printf("error retrieving car id=%s: %v", id, err)
		httpx.HandleServiceError(w, err)
		return
	}

	resp := dto.ToResponse(&car)

	if err := httpx.JSON(w, http.StatusOK, resp); err != nil {
		log.Printf("error encoding car response: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	log.Printf("car retrieved id=%s", id)
}

// List handles retrieving all available cars.
//
// Method: GET
// Path: /cars
func (c *CarController) List(w http.ResponseWriter, r *http.Request) {
	log := logger.FromContext(r.Context())

	filters, err := parseCarFilters(r.URL.Query())
	if err != nil {
		log.Printf("error parsing car filters: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	cars, err := c.service.List(filters)
	if err != nil {
		log.Printf("error retrieving cars: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	resp := dto.ToResponseList(cars)

	if err := httpx.JSON(w, http.StatusOK, resp); err != nil {
		log.Printf("error encoding cars response: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	log.Printf("%d cars retrieved", len(cars))
}

// Create handles creating a new car.
//
// The request body must contain all required car fields.
// The car ID is generated by the system and returned in the response.
//
// Method: POST
// Path: /cars
func (c *CarController) Create(w http.ResponseWriter, r *http.Request) {
	log := logger.FromContext(r.Context())

	req, err := httpx.Decode[dto.CreateCarRequest](r)
	if err != nil {
		log.Printf("error decoding car payload: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	car := dto.ToModelCreate(*req)

	if err := c.service.Create(car); err != nil {
		log.Printf("error creating car: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	resp := dto.ToResponse(car)

	if err := httpx.JSON(w, http.StatusCreated, resp); err != nil {
		log.Printf("error encoding created car response: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	log.Printf("car created id=%s", car.ID)
}

// Update handles updating an existing car.
//
// This endpoint performs a FULL replacement of the car resource.
// All fields must be provided in the request body.
//
// Any field omitted from the request will be reset to its zero value.
// Partial updates are NOT supported.
//
// Method: PUT
// Path: /cars/{id}
func (c *CarController) Update(w http.ResponseWriter, r *http.Request) {
	log := logger.FromContext(r.Context())

	id := chi.URLParam(r, "id")

	req, err := httpx.Decode[dto.UpdateCarRequest](r)
	if err != nil {
		log.Printf("error decoding car payload: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	car := dto.ToModelUpdate(id, *req)

	if err := c.service.Update(car); err != nil {
		log.Printf("error updating car id=%s: %v", car.ID, err)
		httpx.HandleServiceError(w, err)
		return
	}

	resp := dto.ToResponse(car)

	if err := httpx.JSON(w, http.StatusOK, resp); err != nil {
		log.Printf("error encoding updated car response: %v", err)
		httpx.HandleServiceError(w, err)
		return
	}

	log.Printf("car updated id=%s", id)
}

// parseCarFilters converts URL query parameters into a CarFilters struct.
func parseCarFilters(q url.Values) (models.CarFilters, error) {
	f := models.CarFilters{
		Make:  q.Get("make"),
		Model: q.Get("model"),
	}

	if yearStr := q.Get("year"); yearStr != "" {
		year, err := strconv.Atoi(yearStr)
		if err != nil {
			return f, e.NewValidationError(fmt.Errorf("invalid year: %q", yearStr))
		}
		f.Year = year
	}

	return f, nil
}
