package models

import (
	"errors"
	"strings"
	"time"
)

var (
	// ErrCarIDMustBeEmpty is returned when a car ID is provided during creation.
	// The ID must be empty because it is generated by the system.
	ErrCarIDMustBeEmpty = errors.New("id must be empty on create")

	// ErrCarIDRequiredForUpdate is returned when attempting to update a car
	// without providing an ID. An ID is required to identify the existing
	// resource being modified.
	ErrCarIDRequiredForUpdate = errors.New("id is required for update")

	// ErrCarMakeRequired is returned when a car is validated without a make.
	// The make field is mandatory for both creation and update operations.
	ErrCarMakeRequired = errors.New("make is required")

	// ErrCarModelRequired is returned when a car is validated without a model.
	// The model field is mandatory for both creation and update operations.
	ErrCarModelRequired = errors.New("model is required")

	// ErrCarColorRequired is returned when a car is validated without a color.
	// The color field is mandatory for both creation and update operations.
	ErrCarColorRequired = errors.New("color is required")

	// ErrCarCategoryRequired is returned when a car is validated without a category.
	// The category field is mandatory for both creation and update operations.
	ErrCarCategoryRequired = errors.New("category is required")

	// ErrInvalidYear is returned when a car is validated with an invalid year.
	// The year field is mandatory for both creation and update operations.
	ErrInvalidYear = errors.New("year is not valid")

	// ErrInvalidMileage is returned when a car is validated with an invalid mileage.
	// The mileage cannot be negative.
	ErrInvalidMileage = errors.New("mileage cannot be negative")

	// ErrInvalidPrice is returned when a car is validated with an invalid price.
	// The price cannot be negative.
	ErrInvalidPrice = errors.New("price cannot be negative")
)

// Car represents a vehicle with various attributes such as make, model, package, color, category, year, mileage, and price.
type Car struct {
	ID string // Unique identifier for the car.

	Make     string  // Manufacturer of the car (e.g., Toyota, Ford).
	Model    string  // Model name of the car (e.g., Camry, F-10).
	Package  *string // Package level (e.g., SE, XSE).
	Color    string  // Exterior color of the car.
	Category string  // Vehicle category (e.g., SUV, Sedan, Truck).
	Year     int     // Manufacturing year of the car.

	Mileage *int64 // Distance the car has traveled, measured in miles.
	Price   *int64 // Price of the car in cents.
}

// Cars represents a collection of Car objects.
type Cars []Car

func (c Car) ValidateForCreate() error {
	if c.ID != "" {
		return ErrCarIDMustBeEmpty
	}
	return c.validate()
}

func (c Car) ValidateForUpdate() error {
	if strings.TrimSpace(c.ID) == "" {
		return ErrCarIDRequiredForUpdate
	}
	return c.validate()
}

// Validate checks that all required fields in the Car struct are present and valid.
func (c Car) validate() error {
	if strings.TrimSpace(c.Make) == "" {
		return ErrCarMakeRequired
	}

	if strings.TrimSpace(c.Model) == "" {
		return ErrCarModelRequired
	}

	if strings.TrimSpace(c.Color) == "" {
		return ErrCarColorRequired
	}

	if strings.TrimSpace(c.Category) == "" {
		return ErrCarCategoryRequired
	}

	currentYear := time.Now().Year()
	if c.Year <= 0 || c.Year > currentYear {
		return ErrInvalidYear
	}

	if c.Mileage != nil {
		if *c.Mileage < 0 {
			return ErrInvalidMileage
		}
	}

	if c.Price != nil {
		if *c.Price < 0 {
			return ErrInvalidPrice
		}
	}
	return nil
}
